source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DYARippleView_Example', :exclusive => true do
  pod 'DYARippleView', :path => '../'
end

target 'DYARippleView_Tests', :exclusive => true do
  pod 'DYARippleView', :path => '../'

  
end
